### ISSUE TITLE
A couple of Questions

### ISSUE THREAD

**Issue by EomAA** [salazardetroya/bridge_post#1]
Hi,

Thank you for this great post!!
I have a couple of questions about this as follows.

Q1) You mentioned above for a reason to use the Firedrake that “Firedrake” is more integrated with the PETSc library,which is very helpful for setting solver options required for large scale problems. I am just wondering if you had a chance to solve the same or similar problem using “FEniCS”. If so, what’s the main differences? If someone wants to use the FEniCS rather than Firedrake, can I guess that is not only a general implementation including solver setting more tricky but also computational speed slower?

Q2) In this bridge example, are you using a parallel solver based on MPI?

Q3) How the function”DirichletBC()” and the UFLs “dx()” and “ds()” recognize the boundary and domain markers? It seems that you just define the specified numbers for the boundary and domain, but not the specified locations. Are the information defined in the Gmsh file, “bridge.geo”?

Q4) Is it possible to define the boundary marker and domain marker separately? I mean that can we define the boundary markers from 0 to N_bd and the domain markers from 0 to N_domain, respectively, like below;

“For domains”
DECK = 0
DOMAIN = 1 

“For boundaries”
SUPPORT = 0
LOAD = 1
SYMMETRY_X = 2
SYMMETRY_Y = 3

Sorry, I am new to this Python-based TO things, so my questions could be a bit silly.

Thank you again for this helpful post!!

**Comment by salazardetroya** [comment]
1) It can be solved with FEniCS and it can run at almost the same speed (for this size) because FEniCS can also use PETSc for the linear solver. The main difference is that setting a customized PETSc solver in FEniCS is a bit more clunky at the moment. It is cleaner with Firedrake.
2) Yes, Firedrake and PETSc use the MPI paradigm. You can call the script with `mpirun -n 20 python3 bridge.py`
3) That is correct. The boundary markers are in the `.geo` file.
4) I think it is possible. I just prefer it this way.
